# FILE: config.yml
# The definitive configuration file for all experiments.
# This YAML format is robust and replaces the error-prone src/config.py.

# ==============================================================================
# 1. PARAMETER GRIDS (Reusable parameter lists)
# ==============================================================================
param_grid:
  bm_deleterious_wide: [0.2, 0.4, 0.6, 0.8, 0.9, 0.95, 1.0]
  bm_deleterious_narrow: [0.75, 0.85, 0.95]
  width_scan: [64, 128, 256, 512]
  phi_scan: [-1.0, -0.5, 0.0, 0.5, 1.0]
  k_total_scan_coarse: [0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0]
  k_total_scan_fine: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1.0]
  patch_width_scan: [30, 60, 120]
  env_bet_hedging:
    0: { b_wt: 1.0 }
    1: { b_wt: 0.0, b_m: 1.0 }

# ==============================================================================
# 2. EXPERIMENT DEFINITIONS
# ==============================================================================
experiments:
  boundary_analysis:
    campaign_id: fig1_boundary_analysis
    run_mode: calibration
    hpc_params: { time: "0-10:00:00", mem: "2G", sims_per_task: 50 }
    param_grid_keys: [bm_deleterious_wide]
    sim_sets:
      - set_id: main
        base_params:
          width: 512
          length: 1024
          k_total: 0.0
          phi: 0.0
          num_replicates: 200
          initial_condition_type: patch
          initial_mutant_patch_size: 128
          max_steps: 2000000
        grid_params:
          b_m: bm_deleterious_wide

  kpz_scaling:
    campaign_id: fig1_kpz_scaling
    run_mode: diffusion
    hpc_params: { time: "0-12:00:00", mem: "4G", sims_per_task: 40 }
    param_grid_keys: [bm_deleterious_wide, width_scan]
    sim_sets:
      - set_id: main
        base_params:
          length: 4096
          k_total: 0.0
          phi: 0.0
          num_replicates: 100
          initial_condition_type: patch
          initial_mutant_patch_size: 0
          max_steps: 5000000
        grid_params:
          b_m: bm_deleterious_wide
          width: width_scan

  phase_diagram:
    campaign_id: fig2_phase_diagram
    run_mode: phase_diagram
    hpc_params: { time: "0-04:00:00", mem: "4G", sims_per_task: 50 }
    param_grid_keys: [bm_deleterious_wide, phi_scan, k_total_scan_coarse]
    sim_sets:
      - set_id: main
        base_params:
          width: 256
          length: 4096
          num_replicates: 50
          warmup_time: 500.0
          num_samples: 200
          sample_interval: 10.0
          initial_condition_type: mixed
        grid_params:
          b_m: bm_deleterious_wide
          phi: phi_scan
          k_total: k_total_scan_coarse

  bet_hedging:
    campaign_id: fig3_bet_hedging
    run_mode: bet_hedging
    hpc_params: { time: "1-00:00:00", mem: "2G", sims_per_task: 25 }
    param_grid_keys: [bm_deleterious_narrow, phi_scan, k_total_scan_fine, patch_width_scan, env_bet_hedging]
    sim_sets:
      - set_id: main
        base_params:
          width: 256
          length: 8192
          initial_condition_type: mixed
          environment_map: env_bet_hedging
          num_replicates: 32
          log_q_interval: 2.0
          warmup_cycles_for_stats: 4
        grid_params:
          b_m: bm_deleterious_narrow
          phi: phi_scan
          k_total: k_total_scan_fine
          patch_width: patch_width_scan

  relaxation_dynamics:
    campaign_id: fig4_relaxation
    run_mode: relaxation
    hpc_params: { time: "0-06:00:00", mem: "2G", sims_per_task: 40 }
    param_grid_keys: [bm_deleterious_wide, k_total_scan_coarse]
    sim_sets:
      - set_id: main
        base_params:
          width: 256
          length: 8192
          phi: 0.0 # Symmetric switching for this test
          num_replicates: 50
          initial_condition_type: patch
          initial_mutant_patch_size: width # Start with all mutants
          total_run_time: 4000.0
          sample_interval: 15.0
        grid_params:
          b_m: bm_deleterious_wide
          k_total: k_total_scan_coarse